spring.application.name=mini-erp-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/mini-erp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true

jwt.secret=MI_SECRETO_123456789_QUE_ES_LARGO_32_BYTES
jwt.expiration=3600000